name: Gemini Documentation
description: Complete documentation for Gemini Project and Issue Tracker

safe: false
permalink: /:title

port: 5000

plugins:     ./_source/_plugins
source:      ./_source 
destination: ./gemini
